In [1]:
import ast
import pandas as pd
import pickle

In [2]:
credits = pd.read_csv('../data/tmdb_5000_credits.csv')

In [3]:
def parse_cast(cast_str):
    try:
        return ast.literal_eval(cast_str)
    except:
        return []

In [4]:
data = pd.read_pickle('../models/cleaned_movie_data.pkl')

In [5]:
data['cast_parsed'] = credits['cast'].apply(parse_cast)

In [6]:
data["cast_parsed"]

0       [{'cast_id': 242, 'character': 'Jake Sully', '...
1       [{'cast_id': 4, 'character': 'Captain Jack Spa...
2       [{'cast_id': 1, 'character': 'James Bond', 'cr...
3       [{'cast_id': 2, 'character': 'Bruce Wayne / Ba...
4       [{'cast_id': 5, 'character': 'John Carter', 'c...
                              ...
4798    [{'cast_id': 1, 'character': 'El Mariachi', 'c...
4799    [{'cast_id': 1, 'character': 'Buzzy', 'credit_...
4800    [{'cast_id': 8, 'character': 'Oliver O’Toole',...
4801    [{'cast_id': 3, 'character': 'Sam', 'credit_id...
4802    [{'cast_id': 3, 'character': 'Herself', 'credi...
Name: cast_parsed, Length: 4803, dtype: object

In [12]:
data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,vote_average,vote_count,cast,crew,genres_collapsed,keywords_collapsed,cast_collapsed,overview_cleaned,tags,cast_parsed
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,7.2,11800,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B...",ActionAdventureFantasyScienceFiction,cultureclashfuturespacewarspacecolonysocietysp...,SamWorthingtonZoeSaldanaSigourneyWeaver,"in the 22nd century, a paraplegic marine is di...",ActionAdventureFantasyScienceFiction culturecl...,"[{'cast_id': 242, 'character': 'Jake Sully', '..."
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,6.9,4500,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...",AdventureFantasyAction,oceandrugabuseexoticislandeastindiatradingcomp...,JohnnyDeppOrlandoBloomKeiraKnightley,"captain barbossa, long believed to be dead, ha...",AdventureFantasyAction oceandrugabuseexoticisl...,"[{'cast_id': 4, 'character': 'Captain Jack Spa..."
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,6.3,4466,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Thomas Newman, Sam Mendes, Anna Pinnock, John...",ActionAdventureCrime,spybasedonnovelsecretagentsequelmi6britishsecr...,DanielCraigChristophWaltzLéaSeydoux,a cryptic message from bond’s past sends him o...,ActionAdventureCrime spybasedonnovelsecretagen...,"[{'cast_id': 1, 'character': 'James Bond', 'cr..."
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,7.6,9106,"[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Charles Roven, Christopher Nolan...",ActionCrimeDramaThriller,dccomicscrimefighterterroristsecretidentitybur...,ChristianBaleMichaelCaineGaryOldman,following the death of district attorney harve...,ActionCrimeDramaThriller dccomicscrimefightert...,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba..."
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,6.1,2124,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Andrew Stanton, John Lasseter...",ActionAdventureScienceFiction,basedonnovelmarsmedallionspacetravelprincessal...,TaylorKitschLynnCollinsSamanthaMorton,"john carter is a war-weary, former military ca...",ActionAdventureScienceFiction basedonnovelmars...,"[{'cast_id': 5, 'character': 'John Carter', 'c..."

In [7]:
print(type(data["cast_parsed"][0]))

<class 'list'>

In [8]:
cast_rows = []

for _, row in data.iterrows():
    movie_id = row['id']
    movie_title = row['title']
    
    for cast in row['cast_parsed']:
        cast_rows.append({
            "cast_id": cast.get("cast_id"),
            "person_id": cast.get("id"),
            "name": cast.get("name"),
            "character": cast.get("character"),
            "order": cast.get("order"),
            "movie_id": movie_id,
            "movie_title": movie_title   
        })

cast_df = pd.DataFrame(cast_rows)

In [11]:
cast_df

,cast_id,person_id,name,character,order,movie_id,movie_title
0,242,65731,Sam Worthington,Jake Sully,0,19995,Avatar
1,3,8691,Zoe Saldana,Neytiri,1,19995,Avatar
2,25,10205,Sigourney Weaver,Dr. Grace Augustine,2,19995,Avatar
3,4,32747,Stephen Lang,Col. Quaritch,3,19995,Avatar
4,5,17647,Michelle Rodriguez,Trudy Chacon,4,19995,Avatar
...,...,...,...,...,...,...,...
106252,8,21315,Eric Roberts,Himself,3,25975,My Date with Drew
106253,9,2171,Griffin Dunne,Himself,4,25975,My Date with Drew
106254,10,2231,Samuel L. Jackson,Himself,5,25975,My Date with Drew
106255,11,14407,Matt LeBlanc,Himself,6,25975,My Date with Drew
106256,7,155007,Bill D'Elia,Himself,7,25975,My Date with Drew

In [9]:
cast_df[cast_df['name'] == "Leonardo DiCaprio"]['movie_title']

1407                         Titanic
2729                The Great Gatsby
4750                       Inception
7802                    The Revenant
10025                    The Aviator
11358               Django Unchained
11670                  Blood Diamond
11692        The Wolf of Wall Street
12270              Gangs of New York
13324                   The Departed
16001                 Shutter Island
21283                   Body of Lies
28784            Catch Me If You Can
31015                      The Beach
33844             Revolutionary Road
41276       The Man in the Iron Mask
41937                       J. Edgar
44552         The Quick and the Dead
56331                  Marvin's Room
71326                 Romeo + Juliet
75745                      Celebrity
77369    What's Eating Gilbert Grape
Name: movie_title, dtype: object

In [10]:
cast_df

,cast_id,person_id,name,character,order,movie_id,movie_title
0,242,65731,Sam Worthington,Jake Sully,0,19995,Avatar
1,3,8691,Zoe Saldana,Neytiri,1,19995,Avatar
2,25,10205,Sigourney Weaver,Dr. Grace Augustine,2,19995,Avatar
3,4,32747,Stephen Lang,Col. Quaritch,3,19995,Avatar
4,5,17647,Michelle Rodriguez,Trudy Chacon,4,19995,Avatar
...,...,...,...,...,...,...,...
106252,8,21315,Eric Roberts,Himself,3,25975,My Date with Drew
106253,9,2171,Griffin Dunne,Himself,4,25975,My Date with Drew
106254,10,2231,Samuel L. Jackson,Himself,5,25975,My Date with Drew
106255,11,14407,Matt LeBlanc,Himself,6,25975,My Date with Drew
106256,7,155007,Bill D'Elia,Himself,7,25975,My Date with Drew